[build]
  command = "(pnpm install && build:netlify) || ( npm install pnpm && pnpm install && pnpm build:netlify )"
  publish = "build/"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

