name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: build
        run: |
          npm install
          npm run build:static
        
      - name: copy
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          target: ${{ secrets.SSH_TARGET }}
          source: "./build/*"
          strip_components: 1