name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: []

      - name: Use Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: lint, check, build
        run: |
          pnpm lint --scope web
          pnpm check --scope web

      - name: copy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          target: ${{ secrets.SSH_TARGET }}
          source: 'apps/web/build/*'
          strip_components: 3
          rm: true

      - name: symlink
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.SSH_TARGET }}
            ln -sf ../shop/ebay_2 ./ebay_2
            ln -sf ../shop/ebay_3 ./ebay_3
            ln -sf ../shop/ebay_4 ./ebay_4
            ln -sf ../shop/skydd ./skydd
